In [127]:
from pandas import read_csv
import numpy as np
from keras import Model
from keras.layers import Layer
import keras.backend as K
from keras.layers import Input, Dense, SimpleRNN
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.metrics import mean_squared_error

In [128]:
# Prepare data
def generate_fibonacci_sequence(num_elements, scale_data=True):
#def generate_fibonacci_sequence(num_elements, scale_data=False):
    # Get the Fibonacci sequence
    fibonacci_sequence = np.zeros(num_elements)
    fib_n1 = 0.0
    fib_n = 1.0 
    for i in range(num_elements):
            fibonacci_sequence[i] = fib_n1 + fib_n
            #fib_n1 = fib_n
            fib_n1 = 2
            fib_n = fibonacci_sequence[i] 
    data_scaler = []
    if scale_data:
        data_scaler = MinMaxScaler(feature_range=(0, 1))
        fibonacci_sequence = np.reshape(fibonacci_sequence, (num_elements, 1))
        fibonacci_sequence = data_scaler.fit_transform(fibonacci_sequence).flatten()        
    return fibonacci_sequence, data_scaler
def generate_fibonacci_dataset(total_fib_numbers, time_steps, train_percent, scale_data=True):
#def generate_fibonacci_dataset(total_fib_numbers, time_steps, train_percent, scale_data=False):
    data, data_scaler = generate_fibonacci_sequence(total_fib_numbers, scale_data)    
    Y_indices = np.arange(time_steps, len(data), 1)
    Y = data[Y_indices]
    num_rows_x = len(Y)
    X = data[0:num_rows_x]
    for i in range(time_steps-1):
        temp = data[i+1:num_rows_x+i+1]
        X = np.column_stack((X, temp))
    # random permutation with fixed seed   
    random_generator = np.random.RandomState(seed=13)
    indices = random_generator.permutation(num_rows_x)
    split_index = int(train_percent*num_rows_x)
    train_indices = indices[0:split_index]
    test_indices = indices[split_index:]
    trainX = X[train_indices]
    trainY = Y[train_indices]
    testX = X[test_indices]
    testY = Y[test_indices]
    trainX = np.reshape(trainX, (len(trainX), time_steps, 1))    
    testX = np.reshape(testX, (len(testX), time_steps, 1))
    return trainX, trainY, testX, testY, data_scaler

In [129]:
# Set up parameters
time_steps = 20
#time_steps = 3
hidden_units = 2
#epochs = 30
#epochs = 50
epochs = 500

In [131]:
# Create a traditional RNN network
def create_RNN_model(hidden_units, dense_units, input_shape, activation):
    rnn_model = Sequential()
    rnn_model.add(SimpleRNN(hidden_units, input_shape=input_shape, activation=activation[0]))
    rnn_model.add(Dense(units=dense_units, activation=activation[1]))
    rnn_model.compile(loss='mse', optimizer='adam')
    return rnn_model

rnn_model = create_RNN_model(hidden_units=hidden_units, dense_units=1, input_shape=(time_steps,1), 
                   activation=['tanh', 'tanh'])

# Generate the dataset for the network
#trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(1200, time_steps, 0.7)
trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(2000, time_steps, 0.95)
#trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(10, time_steps, 0.8)
#trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(50, time_steps, 0.8)
#trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(20, time_steps, 0.8)
#trainX, trainY, testX, testY, data_scaler  = generate_fibonacci_dataset(20, time_steps, 0.95)
# Train the network

#trainX, trainY

In [111]:
#data_scaler

In [132]:
#rnn_model.fit(trainX, trainY, epochs=epochs, batch_size=1, verbose=2)
#rnn_model.fit(trainX, trainY, epochs=epochs, verbose=10)
rnn_model.fit(trainX, trainY, epochs=epochs)
# Evaluate model
train_error = rnn_model.evaluate(trainX, trainY)
test_error = rnn_model.evaluate(testX, testY)

# Print error
print("Train set MSE = ", train_error)
print("Test set MSE = ", test_error)

Epoch 1/500
59/59 [==============================] - 1s 3ms/step - loss: 0.0456
Epoch 2/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0249
Epoch 3/500
59/59 [==============================] - 0s 4ms/step - loss: 0.0169
Epoch 4/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0126
Epoch 5/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0099
Epoch 6/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0079
Epoch 7/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0066
Epoch 8/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0058
Epoch 9/500
59/59 [==============================] - 0s 4ms/step - loss: 0.0052
Epoch 10/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0047
Epoch 11/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0042
Epoch 12/500
59/59 [==============================] - 0s 3ms/step - loss: 0.0038
Epoch 13/500
59/59 [=================

59/59 [==============================] - 0s 4ms/step - loss: 1.4207e-04
Epoch 100/500
59/59 [==============================] - 0s 4ms/step - loss: 1.3774e-04
Epoch 101/500
59/59 [==============================] - 0s 4ms/step - loss: 1.3392e-04
Epoch 102/500
59/59 [==============================] - 0s 4ms/step - loss: 1.3178e-04
Epoch 103/500
59/59 [==============================] - 0s 4ms/step - loss: 1.2752e-04
Epoch 104/500
59/59 [==============================] - 0s 4ms/step - loss: 1.2385e-04
Epoch 105/500
59/59 [==============================] - 0s 4ms/step - loss: 1.2009e-04
Epoch 106/500
59/59 [==============================] - 0s 3ms/step - loss: 1.1802e-04
Epoch 107/500
59/59 [==============================] - 0s 4ms/step - loss: 1.1452e-04
Epoch 108/500
59/59 [==============================] - 0s 4ms/step - loss: 1.1210e-04
Epoch 109/500
59/59 [==============================] - 0s 4ms/step - loss: 1.0910e-04
Epoch 110/500
59/59 [==============================] - 0s 4ms/step -

59/59 [==============================] - 0s 4ms/step - loss: 4.1330e-05
Epoch 195/500
59/59 [==============================] - 0s 4ms/step - loss: 4.0123e-05
Epoch 196/500
59/59 [==============================] - 0s 4ms/step - loss: 4.0422e-05
Epoch 197/500
59/59 [==============================] - 0s 4ms/step - loss: 4.0727e-05
Epoch 198/500
59/59 [==============================] - 0s 4ms/step - loss: 3.9976e-05
Epoch 199/500
59/59 [==============================] - 0s 4ms/step - loss: 4.3248e-05
Epoch 200/500
59/59 [==============================] - 0s 4ms/step - loss: 4.0084e-05
Epoch 201/500
59/59 [==============================] - 0s 3ms/step - loss: 4.0097e-05
Epoch 202/500
59/59 [==============================] - 0s 3ms/step - loss: 4.1882e-05
Epoch 203/500
59/59 [==============================] - 0s 3ms/step - loss: 3.9321e-05
Epoch 204/500
59/59 [==============================] - 0s 3ms/step - loss: 4.0302e-05
Epoch 205/500
59/59 [==============================] - 0s 4ms/step -

59/59 [==============================] - 0s 3ms/step - loss: 3.8141e-05
Epoch 290/500
59/59 [==============================] - 0s 3ms/step - loss: 3.9094e-05
Epoch 291/500
59/59 [==============================] - 0s 3ms/step - loss: 3.6895e-05
Epoch 292/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7217e-05
Epoch 293/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8719e-05
Epoch 294/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7837e-05
Epoch 295/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8140e-05
Epoch 296/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8208e-05
Epoch 297/500
59/59 [==============================] - 0s 3ms/step - loss: 4.1820e-05
Epoch 298/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7769e-05
Epoch 299/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8026e-05
Epoch 300/500
59/59 [==============================] - 0s 4ms/step -

59/59 [==============================] - 0s 3ms/step - loss: 3.9364e-05
Epoch 385/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5756e-05
Epoch 386/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7477e-05
Epoch 387/500
59/59 [==============================] - 0s 3ms/step - loss: 3.6559e-05
Epoch 388/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7115e-05
Epoch 389/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7194e-05
Epoch 390/500
59/59 [==============================] - 0s 3ms/step - loss: 3.6341e-05
Epoch 391/500
59/59 [==============================] - 0s 3ms/step - loss: 3.6956e-05
Epoch 392/500
59/59 [==============================] - 0s 3ms/step - loss: 3.7455e-05
Epoch 393/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8500e-05
Epoch 394/500
59/59 [==============================] - 0s 3ms/step - loss: 3.8263e-05
Epoch 395/500
59/59 [==============================] - 0s 3ms/step -

59/59 [==============================] - 0s 3ms/step - loss: 3.6529e-05
Epoch 480/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5840e-05
Epoch 481/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5637e-05
Epoch 482/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5701e-05
Epoch 483/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5067e-05
Epoch 484/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5396e-05
Epoch 485/500
59/59 [==============================] - 0s 3ms/step - loss: 3.4738e-05
Epoch 486/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5846e-05
Epoch 487/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5638e-05
Epoch 488/500
59/59 [==============================] - 0s 3ms/step - loss: 3.9026e-05
Epoch 489/500
59/59 [==============================] - 0s 3ms/step - loss: 3.5422e-05
Epoch 490/500
59/59 [==============================] - 0s 3ms/step -

In [137]:
testY[6], testX[6]

(0.3366683341670835,
 array([[0.32666333],
        [0.32716358],
        [0.32766383],
        [0.32816408],
        [0.32866433],
        [0.32916458],
        [0.32966483],
        [0.33016508],
        [0.33066533],
        [0.33116558],
        [0.33166583],
        [0.33216608],
        [0.33266633],
        [0.33316658],
        [0.33366683],
        [0.33416708],
        [0.33466733],
        [0.33516758],
        [0.33566783],
        [0.33616808]]))

In [138]:
data_scaler.inverse_transform(np.array(testX[6]))#,data_scaler.inverse_transform(testX[3])

array([[1307.],
       [1309.],
       [1311.],
       [1313.],
       [1315.],
       [1317.],
       [1319.],
       [1321.],
       [1323.],
       [1325.],
       [1327.],
       [1329.],
       [1331.],
       [1333.],
       [1335.],
       [1337.],
       [1339.],
       [1341.],
       [1343.],
       [1345.]])

In [139]:
rnn_model.predict(np.array([testX[6]]))
#array([[0.9642479]], dtype=float32)


1/1 [==============================] - 0s 26ms/step


array([[0.3353087]], dtype=float32)

In [140]:
data_scaler.inverse_transform([[0.3353087]])

array([[1341.5641826]])

In [141]:
rnn_model.save_weights('Attention Basic Example -  2024_01_19 wo Attention.h5')

In [142]:
# Add attention layer to the deep learning network
class AttentionLayer(Layer):
    def __init__(self,**kwargs):
        super(AttentionLayer,self).__init__(**kwargs)

    def build(self,input_shape):
        self.attention_weights=self.add_weight(name='attention_weight', shape=(input_shape[-1],1), 
                               initializer='random_normal', trainable=True)
        self.attention_bias=self.add_weight(name='attention_bias', shape=(input_shape[1],1), 
                               initializer='zeros', trainable=True)        
        super(AttentionLayer, self).build(input_shape)

    def call(self,x):
        # Alignment scores. Pass them through tanh function
        alignment_scores = K.tanh(K.dot(x,self.attention_weights)+self.attention_bias)
        # Remove dimension of size 1
        alignment_scores = K.squeeze(alignment_scores, axis=-1)   
        # Compute the weights
        alpha = K.softmax(alignment_scores)
        # Reshape to tensorFlow format
        alpha = K.expand_dims(alpha, axis=-1)
        # Compute the context vector
        context_vector = x * alpha
        context_vector = K.sum(context_vector, axis=1)
        return context_vector

In [143]:
model_RNN = create_RNN_model(hidden_units=hidden_units, dense_units=1, input_shape=(time_steps,1), 
                   activation=['tanh', 'tanh'])


In [144]:
def create_RNN_with_attention(hidden_units, dense_units, input_shape, activation):
    input_layer=Input(shape=input_shape)
    rnn_layer = SimpleRNN(hidden_units, return_sequences=True, activation=activation)(input_layer)
    attention_layer = AttentionLayer()(rnn_layer)
    output_layer=Dense(dense_units, trainable=True, activation=activation)(attention_layer)
    rnn_attention_model=Model(input_layer,output_layer)
    rnn_attention_model.compile(loss='mse', optimizer='adam')  
    return rnn_attention_model 


In [145]:
# Create the model with attention, train and evaluate
rnn_attention_model = create_RNN_with_attention(hidden_units=hidden_units, dense_units=1, 
                                  input_shape=(time_steps,1), activation='tanh')
rnn_attention_model.summary()    
#rnn_attention_model.fit(trainX, trainY, epochs=epochs, batch_size=1, verbose=2)
rnn_attention_model.fit(trainX, trainY, epochs=epochs, verbose=2)
# Evaluate model
train_error_with_attention = rnn_attention_model.evaluate(trainX, trainY)
test_error_with_attention = rnn_attention_model.evaluate(testX, testY)

# Print error
print("Train set MSE with attention = ", train_error_with_attention)
print("Test set MSE with attention = ", test_error_with_attention)


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 20, 1)]           0         
                                                                 
 simple_rnn_17 (SimpleRNN)   (None, 20, 2)             8         
                                                                 
 attention_layer (AttentionL  (None, 2)                22        
 ayer)                                                           
                                                                 
 dense_17 (Dense)            (None, 1)                 3         
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
59/59 - 1s - loss: 0.3838 - 1s/epoch - 17ms/step
Epoch 2/500
59/59 - 0s - loss: 0.2369 - 167ms/epoch - 3ms/step
Epoch 3

Epoch 111/500
59/59 - 0s - loss: 2.8753e-04 - 208ms/epoch - 4ms/step
Epoch 112/500
59/59 - 0s - loss: 2.7739e-04 - 181ms/epoch - 3ms/step
Epoch 113/500
59/59 - 0s - loss: 2.7046e-04 - 159ms/epoch - 3ms/step
Epoch 114/500
59/59 - 0s - loss: 2.6234e-04 - 188ms/epoch - 3ms/step
Epoch 115/500
59/59 - 0s - loss: 2.5586e-04 - 205ms/epoch - 3ms/step
Epoch 116/500
59/59 - 0s - loss: 2.5012e-04 - 199ms/epoch - 3ms/step
Epoch 117/500
59/59 - 0s - loss: 2.4223e-04 - 170ms/epoch - 3ms/step
Epoch 118/500
59/59 - 0s - loss: 2.3622e-04 - 169ms/epoch - 3ms/step
Epoch 119/500
59/59 - 0s - loss: 2.2923e-04 - 173ms/epoch - 3ms/step
Epoch 120/500
59/59 - 0s - loss: 2.2399e-04 - 192ms/epoch - 3ms/step
Epoch 121/500
59/59 - 0s - loss: 2.1670e-04 - 197ms/epoch - 3ms/step
Epoch 122/500
59/59 - 0s - loss: 2.1167e-04 - 176ms/epoch - 3ms/step
Epoch 123/500
59/59 - 0s - loss: 2.0562e-04 - 172ms/epoch - 3ms/step
Epoch 124/500
59/59 - 0s - loss: 1.9996e-04 - 155ms/epoch - 3ms/step
Epoch 125/500
59/59 - 0s - loss: 1

Epoch 230/500
59/59 - 0s - loss: 2.0085e-05 - 157ms/epoch - 3ms/step
Epoch 231/500
59/59 - 0s - loss: 1.9553e-05 - 184ms/epoch - 3ms/step
Epoch 232/500
59/59 - 0s - loss: 1.9383e-05 - 212ms/epoch - 4ms/step
Epoch 233/500
59/59 - 0s - loss: 1.8946e-05 - 173ms/epoch - 3ms/step
Epoch 234/500
59/59 - 0s - loss: 1.8833e-05 - 165ms/epoch - 3ms/step
Epoch 235/500
59/59 - 0s - loss: 1.8409e-05 - 173ms/epoch - 3ms/step
Epoch 236/500
59/59 - 0s - loss: 1.8446e-05 - 168ms/epoch - 3ms/step
Epoch 237/500
59/59 - 0s - loss: 1.7788e-05 - 162ms/epoch - 3ms/step
Epoch 238/500
59/59 - 0s - loss: 1.7488e-05 - 180ms/epoch - 3ms/step
Epoch 239/500
59/59 - 0s - loss: 1.7609e-05 - 171ms/epoch - 3ms/step
Epoch 240/500
59/59 - 0s - loss: 1.7645e-05 - 201ms/epoch - 3ms/step
Epoch 241/500
59/59 - 0s - loss: 1.6742e-05 - 158ms/epoch - 3ms/step
Epoch 242/500
59/59 - 0s - loss: 1.7102e-05 - 158ms/epoch - 3ms/step
Epoch 243/500
59/59 - 0s - loss: 1.6186e-05 - 167ms/epoch - 3ms/step
Epoch 244/500
59/59 - 0s - loss: 1

Epoch 349/500
59/59 - 0s - loss: 3.0341e-06 - 179ms/epoch - 3ms/step
Epoch 350/500
59/59 - 0s - loss: 2.9006e-06 - 185ms/epoch - 3ms/step
Epoch 351/500
59/59 - 0s - loss: 2.9240e-06 - 190ms/epoch - 3ms/step
Epoch 352/500
59/59 - 0s - loss: 3.0944e-06 - 228ms/epoch - 4ms/step
Epoch 353/500
59/59 - 0s - loss: 2.9125e-06 - 208ms/epoch - 4ms/step
Epoch 354/500
59/59 - 0s - loss: 2.8986e-06 - 195ms/epoch - 3ms/step
Epoch 355/500
59/59 - 0s - loss: 2.7948e-06 - 195ms/epoch - 3ms/step
Epoch 356/500
59/59 - 0s - loss: 2.8124e-06 - 173ms/epoch - 3ms/step
Epoch 357/500
59/59 - 0s - loss: 2.6864e-06 - 202ms/epoch - 3ms/step
Epoch 358/500
59/59 - 0s - loss: 2.7473e-06 - 171ms/epoch - 3ms/step
Epoch 359/500
59/59 - 0s - loss: 2.5802e-06 - 225ms/epoch - 4ms/step
Epoch 360/500
59/59 - 0s - loss: 2.5811e-06 - 235ms/epoch - 4ms/step
Epoch 361/500
59/59 - 0s - loss: 2.6038e-06 - 264ms/epoch - 4ms/step
Epoch 362/500
59/59 - 0s - loss: 2.6070e-06 - 259ms/epoch - 4ms/step
Epoch 363/500
59/59 - 0s - loss: 2

Epoch 468/500
59/59 - 0s - loss: 1.4864e-06 - 206ms/epoch - 3ms/step
Epoch 469/500
59/59 - 0s - loss: 1.4015e-06 - 194ms/epoch - 3ms/step
Epoch 470/500
59/59 - 0s - loss: 1.4132e-06 - 207ms/epoch - 4ms/step
Epoch 471/500
59/59 - 0s - loss: 1.4105e-06 - 184ms/epoch - 3ms/step
Epoch 472/500
59/59 - 0s - loss: 1.4211e-06 - 208ms/epoch - 4ms/step
Epoch 473/500
59/59 - 0s - loss: 1.4685e-06 - 201ms/epoch - 3ms/step
Epoch 474/500
59/59 - 0s - loss: 1.3708e-06 - 210ms/epoch - 4ms/step
Epoch 475/500
59/59 - 0s - loss: 1.5220e-06 - 205ms/epoch - 3ms/step
Epoch 476/500
59/59 - 0s - loss: 1.3811e-06 - 213ms/epoch - 4ms/step
Epoch 477/500
59/59 - 0s - loss: 1.5399e-06 - 196ms/epoch - 3ms/step
Epoch 478/500
59/59 - 0s - loss: 1.5551e-06 - 194ms/epoch - 3ms/step
Epoch 479/500
59/59 - 0s - loss: 1.4136e-06 - 208ms/epoch - 4ms/step
Epoch 480/500
59/59 - 0s - loss: 1.4772e-06 - 214ms/epoch - 4ms/step
Epoch 481/500
59/59 - 0s - loss: 1.3645e-06 - 208ms/epoch - 4ms/step
Epoch 482/500
59/59 - 0s - loss: 1

In [ ]:
Train set MSE =  3.6586781789083034e-05
Test set MSE =  2.966219835798256e-05

In [146]:
testY[6], testX[6]

(0.3366683341670835,
 array([[0.32666333],
        [0.32716358],
        [0.32766383],
        [0.32816408],
        [0.32866433],
        [0.32916458],
        [0.32966483],
        [0.33016508],
        [0.33066533],
        [0.33116558],
        [0.33166583],
        [0.33216608],
        [0.33266633],
        [0.33316658],
        [0.33366683],
        [0.33416708],
        [0.33466733],
        [0.33516758],
        [0.33566783],
        [0.33616808]]))

In [147]:
data_scaler.inverse_transform(np.array(testX[6]))#,data_scaler.inverse_transform(testX[3])

array([[1307.],
       [1309.],
       [1311.],
       [1313.],
       [1315.],
       [1317.],
       [1319.],
       [1321.],
       [1323.],
       [1325.],
       [1327.],
       [1329.],
       [1331.],
       [1333.],
       [1335.],
       [1337.],
       [1339.],
       [1341.],
       [1343.],
       [1345.]])

In [148]:
rnn_attention_model.predict(np.array([testX[6]]))
#array([[0.9642479]], dtype=float32)

1/1 [==============================] - 0s 175ms/step


array([[0.33799005]], dtype=float32)

In [149]:
data_scaler.inverse_transform([[0.33799005]])

array([[1352.2842199]])